// <auto-generated />
namespace RuffLife.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedwalkoffer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedwalkoffer));
        
        string IMigrationMetadata.Id
        {
            get { return "201605311112358_added-walk-offer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
